name: movie_browser
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.3.0+7

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.4
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  firebase_analytics: ^10.8.5
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_crashlytics: ^3.4.14
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_cache_manager: ^3.3.1
  flutter_facebook_auth: ^6.1.0
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.2.0
  google_sign_in: ^6.2.1
  http: ^1.1.0
  hydrated_bloc: ^9.1.4
  injectable: ^2.3.2
  intl: any
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  photo_view: ^0.14.0
  responsive_framework: ^0.2.0
  shimmer: ^3.0.0
  sign_button: ^2.0.6
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.5
  uuid: ^4.3.3
  youtube_player_iframe: ^5.0.0
  analyzer: ^6.4.1
  path_provider: ^2.1.2

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.3

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/movie_browser.png"
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: "assets/icons/movie_browser_adaptive.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
