name: movie_browser
description: Cool movie browser.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.4.0+9

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bloc_test: ^9.1.7
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.3
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  fake_cloud_firestore: ^2.5.1
  firebase_analytics: ^10.10.5
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_crashlytics: ^3.5.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_cache_manager: ^3.3.2
  flutter_facebook_auth: ^6.2.0
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^13.2.5
  google_sign_in: ^6.2.1
  http: ^1.2.1
  injectable: ^2.4.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.3.0
  mocktail: ^1.0.3
  photo_view: ^0.15.0
  responsive_framework: ^0.2.0
  shimmer: ^3.0.0
  sign_button: ^2.0.6
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  youtube_player_iframe: ^5.1.2

dev_dependencies:
  build_runner:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/movie_browser.png"
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: "assets/icons/movie_browser_adaptive.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
